# Generated by Django 5.2.4 on 2026-08-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testform',
            old_name='passowrd',
            new_name='password',
        ),
    ]
